version: '3'
services:
  
  flaskapp:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: manish
      MYSQL_PASSWORD: password #insert your password
      MYSQL_DB: monkdb
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # insert your root password
      MYSQL_DATABASE: myDb
      MYSQL_USER: manish
      MYSQL_PASSWORD: password #inser your password
    volumes:
      - ./message_table.sql:/docker-entrypoint-initdb.d/message_table.sql   # Mount sql script into container's /docker-entrypoint-initdb.d directory to get table automatically created
      - mysql-data:/var/lib/mysql  # Mount the volume for MySQL data storage

volumes:
  mysql-data:
